### ISSUE TITLE
Error Unsupported Version 144

### ISSUE THREAD

**Issue by djdanby** [Donkie/I3DShapesTool#38]
Everytime i get the same error. I can not extract the shapes file. I use the ShapeTool Version 1.5.0

[FATAL] Unsupported version: 144
Unhandled exception. System.NotSupportedException: Unsupported version
   at I3DShapesTool.Lib.Container.ShapesFileReader..ctor(Stream inputStream, ILogger logger, Nullable`1 forceSeed)
   at I3DShapesTool.Lib.Model.ShapesFile.Load(Stream inputStream, Nullable`1 forceSeed, Boolean strict)
   at I3DShapesTool.Program.LoadFileBruteForce(String filePath)
   at I3DShapesTool.Program.LoadFile(String filePath)
   at I3DShapesTool.Program.ProcessFileInput(CommandLineOptions options)
   at I3DShapesTool.Program.Run(CommandLineOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at I3DShapesTool.Program.Main(String[] args)

**Comment by Donkie** [comment]
What game/DLC? What model?

**Comment by djdanby** [comment]
Pumps and Hoses. The Mobile Separator.

**Comment by djdanby** [comment]
So honestly. I have the feeling that this tool is completely useless. No matter which shape I want to convert so far. Always some error. Already when starting the tool I see errors. And not a single shape could be extracted so far, not from the Kubota Pack. Not from the Expantionpack or anything else. The description for the use of the tool is also extremely poor. Which makes it impossible to understand if i doing something wrong (which I don't think you are). Do I need any additional tools or files for this tool? And if so, which ones?

The First Error what i see is: MissingRequieredOptionError. WHY?

**Comment by Donkie** [comment]
Have you read the readme? It shows a working example on how to provide options. Run the program with -h to get all available options.

Regarding support, Giants updates the model format from time to time with new DLC releases, and that means I need to keep up to speed with that. I am working on this project rather infrequently, and that means it sometimes doesnt support the latest version.

**Comment by djdanby** [comment]
Yes I have read the readme. Several times! And I have also tested several ways. Unfortunately no way works at all.
For me, from the ReadMe is also not apparent whether I need in addition to the "I3DShapesTool.exe" other files. Because there are other folders and files stored here at Github. And if I need them, where should I put the exe file? This is also not clear from the readme.

If it is due to the changes made by Giants, then that would also explain why the current version does not work with the expansion pack.
But if something works... Then here is my next question. Is it possible to convert the shapes only to OBJ or FBX? Or does the shape file become fully functional again so that it can be controlled by the i3d file?

And what about the error message I get right after starting the tool? "MissingRequieredOptionError". Why does this error always occur?

**Comment by Donkie** [comment]
The readme tells you to download the .exe from the releases page. You don't need anything else.

The tool only supports exporting to .obj for the moment.

You need to specify command line options to the exe, you need to run it from cmd. You can't just double click it.

**Comment by tacticalcatboy** [comment]
> So honestly. I have the feeling that this tool is completely useless. No matter which shape I want to convert so far. Always some error. Already when starting the tool I see errors. And not a single shape could be extracted so far, not from the Kubota Pack. Not from the Expantionpack or anything else. The description for the use of the tool is also extremely poor. Which makes it impossible to understand if i doing something wrong (which I don't think you are). Do I need any additional tools or files for this tool? And if so, which ones?
> 
> The First Error what i see is: MissingRequieredOptionError. WHY?

it takes time to update, since those dlcs came out after the last tool release, of course its going to be outdated, but this shit takes time and you just gotta trust the dev on it!

**Comment by kbrandwijk** [comment]
I think the issue you are seeing is the result of incorrectly unpacking the DLC. I have no problem using this tool on any of the files included with this, or any other DLC. Problems start when using an outdated script to extract the DLC in the first place. This to me seems to have nothing to do with this tool, which works fine.
