### ISSUE TITLE
[FATAL] Unsupported version: 15

### ISSUE THREAD

**Issue by tacticalcatboy** [Donkie/I3DShapesTool#39]
PS C:\Users\Scarlett\Downloads\quickbms\test\vehicles\koller\k307> .\I3DShapesTool k307.i3d.shapes
[INFO] File is I3D, parsing data from XML.
[INFO] Loading file: k307.i3d.shapes
[INFO] Failed decrypting file. Attempting to brute-force the seed...
[FATAL] Unsupported version: 15
Unhandled exception. System.NotSupportedException: Unsupported version
   at I3DShapesTool.Lib.Container.ShapesFileReader..ctor(Stream inputStream, ILogger logger, Nullable`1 forceSeed)
   at I3DShapesTool.Lib.Model.ShapesFile.Load(Stream inputStream, Nullable`1 forceSeed, Boolean strict)
   at I3DShapesTool.Program.LoadFileBruteForce(String filePath)
   at I3DShapesTool.Program.LoadFile(String filePath)
   at I3DShapesTool.Program.ProcessFileInput(CommandLineOptions options)
   at I3DShapesTool.Program.Run(CommandLineOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at I3DShapesTool.Program.Main(String[] args)
PS C:\Users\Scarlett\Downloads\quickbms\test\vehicles\koller\k307>

Platinum DLC, using Koller k307

**Comment by kbrandwijk** [comment]
Make sure you are using the correct quickbms script. I have just tested version 1.5.0 of the unlocker with this file, and I have no problem with it.
![image](https://user-images.githubusercontent.com/852069/203036006-d0d57768-ec07-44a8-bb51-6a8feae48e89.png)

**Comment by tacticalcatboy** [comment]
> Make sure you are using the correct quickbms script. I have just tested version 1.5.0 of the unlocker with this file, and I have no problem with it.
> ![image](https://user-images.githubusercontent.com/852069/203036006-d0d57768-ec07-44a8-bb51-6a8feae48e89.png)

could you link the latest quickbms script? i was using 0.3.3

**Comment by Svenstihl2** [comment]
> Make sure you are using the correct quickbms script. I have just tested version 1.5.0 of the unlocker with this file, and I have no problem with it. ![image](https://user-images.githubusercontent.com/852069/203036006-d0d57768-ec07-44a8-bb51-6a8feae48e89.png)

Hello, i have the Quickbms 0.10.1 & 0.7.3 and i have the 1.5.0 and the unlocker make error: 

[FATAL] Unsupported version: 15
Unhandled exception. System.NotSupportedException: Unsupported version plapla...

Btw. i have it.. my shapeUnlocker .. was too old.

**Comment by ninjayx02** [comment]
@Svenstihl2 Could you link the shapeUnlocker,  will this open the forestry DLC?

**Comment by austinthompson2187** [comment]
fatal error. version 10 not supported.
